language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skido/docker-react:1.1 -f Dockerfile.dev .


script: 
  - docker run -e Cl=true skido/docker-react npm run test